name: rio
version: 0.1.0.0
synopsis: Reader+IO monad plus utilities
github: snoyberg/rio
extra-source-files:
- README.md
- ChangeLog.md

dependencies:
- base >= 4.8.2 && < 5
- containers
- unordered-containers
- vector
- bytestring
- text
- unliftio
- typed-process
- hashable
- say
- mtl
- monad-logger

library:
  source-dirs: src
  exposed-modules:
  - Control.Monad.RIO
  - RIO
  - RIO.ByteString
  - RIO.HashMap
  - RIO.HashSet
  - RIO.Map
  - RIO.Set
  - RIO.Vector
  - RIO.Text
  - RIO.Process

executables:
  rio:
    source-dirs: app
    main: Main.hs
    dependencies:
    - rio
