resolver: lts-8.22
packages:
- .
- extra-dep: true
  location:
    git: https://github.com/snoyberg/foreach.git
    commit: 6076471347fc3c6ef9aa1675f6107c1d66aedaf5
extra-deps:
- unliftio-core-0.1.0.0
- unliftio-0.1.0.0
